#!/bin/bash

#
# runs rspec
#

set -ex

# GEM_HOME="$HOME/.gems" gem install bundler --no-ri --no-rdoc
# bundler is installed via apt-get
bundle install --path vendor/bundle
bundle exec rspec spec

echo OK


